const { expect } = require("chai");
const { ethers, fhevm } = require("hardhat");
const { FhevmType } = require("@fhevm/hardhat-plugin");

// NDIMBAL — real yield closes the loop.
//   npx hardhat test test/NdimbalYield.test.js
// The prize is GENERATED by capital working in a confidential Morpho vault (mocked on Sepolia), not
// hand-injected by a sponsor: fundVault -> vault earns yield -> harvestYield skims only the yield into
// the prize -> the winner claims it. Principal stays invested; nothing ever leaks.

const ROUND = 3600, LOCK = 60, MAX = 3;

async function enc(addr, signer, v) {
  const i = await fhevm.createEncryptedInput(addr, signer.address).add64(BigInt(v)).encrypt();
  return { handle: i.handles[0], proof: i.inputProof };
}
const u64 = (h, addr, s) => fhevm.userDecryptEuint(FhevmType.euint64, h, addr, s);

async function deployAll(withVault = true) {
  const [deployer, alice] = await ethers.getSigners();
  const token = await (await ethers.getContractFactory("MockNdimbalToken")).deploy();
  await token.waitForDeployment();
  const tokenAddr = await token.getAddress();
  let vaultAddr = ethers.ZeroAddress, vault = null;
  if (withVault) {
    vault = await (await ethers.getContractFactory("MockConfidentialVault")).deploy(tokenAddr);
    await vault.waitForDeployment();
    vaultAddr = await vault.getAddress();
  }
  const pool = await (await ethers.getContractFactory("NdimbalPool")).deploy(tokenAddr, ROUND, LOCK, MAX, deployer.address, vaultAddr);
  await pool.waitForDeployment();
  const poolAddr = await pool.getAddress();
  return { deployer, alice, token, tokenAddr, vault, vaultAddr, pool, poolAddr };
}
async function mintApprovePool(token, tokenAddr, poolAddr, who, amount) {
  const m = await enc(tokenAddr, who, amount);
  await token.connect(who).mint(who.address, m.handle, m.proof);
  await token.connect(who).setOperator(poolAddr, 2n ** 47n);
}
async function runDraw(pool, batch = 8) {
  const r = await pool.round();
  while ((await pool.drawPhase(r)) < 2n) await pool.drawTickets(batch);
  while ((await pool.drawPhase(r)) < 3n) await pool.drawMax2(batch);
  while ((await pool.drawPhase(r)) < 4n) await pool.drawMax3(batch);
  while ((await pool.drawPhase(r)) < 5n) await pool.drawWinners(batch);
}

describe("NdimbalPool — real yield funds the prize", function () {
  this.timeout(0);

  it("fundVault → accrue → harvestYield → draw: the prize IS the yield (generated, not injected)", async function () {
    const { deployer, alice, token, tokenAddr, vault, poolAddr, pool } = await deployAll();

    // treasury routes 1000 of capital into the confidential vault (principal stays invested & private)
    await mintApprovePool(token, tokenAddr, poolAddr, deployer, 1_000_000);
    const f = await enc(poolAddr, deployer, 1000);
    await pool.connect(deployer).fundVault(f.handle, f.proof);

    // the vault's strategy earns 50 of yield (simulated on the pool's position)
    await vault.accrue(poolAddr, 50);

    // a saver joins (sole depositor -> deterministic winner)
    await mintApprovePool(token, tokenAddr, poolAddr, alice, 1_000_000);
    const d = await enc(poolAddr, alice, 100);
    await pool.connect(alice).deposit(d.handle, d.proof);

    // skim ONLY the yield into the prize (permissionless)
    await pool.harvestYield();

    await ethers.provider.send("evm_increaseTime", [ROUND + 1]);
    await ethers.provider.send("evm_mine", []);
    await runDraw(pool);

    // the prize comes entirely from the harvested yield (50). alice is the sole saver -> grand tier = 50% = 25.
    const claimable = await u64(await pool.claimableOf(0, alice.address), poolAddr, alice);
    expect(claimable).to.equal(25n);

    // and the winner can actually claim it
    const before = await u64(await token.confidentialBalanceOf(alice.address), tokenAddr, alice);
    await pool.connect(alice).claim(0);
    const after = await u64(await token.confidentialBalanceOf(alice.address), tokenAddr, alice);
    expect(after - before).to.equal(25n);
  });

  it("harvestYield is a safe no-op when the vault holds only principal (no yield yet)", async function () {
    const { deployer, alice, token, tokenAddr, poolAddr, pool } = await deployAll();
    await mintApprovePool(token, tokenAddr, poolAddr, deployer, 1_000_000);
    const f = await enc(poolAddr, deployer, 1000);
    await pool.connect(deployer).fundVault(f.handle, f.proof);
    await pool.harvestYield(); // no accrue -> yield is 0, must not revert

    await mintApprovePool(token, tokenAddr, poolAddr, alice, 1_000_000);
    const d = await enc(poolAddr, alice, 100);
    await pool.connect(alice).deposit(d.handle, d.proof);
    await ethers.provider.send("evm_increaseTime", [ROUND + 1]);
    await ethers.provider.send("evm_mine", []);
    await runDraw(pool);
    const claimable = await u64(await pool.claimableOf(0, alice.address), poolAddr, alice);
    expect(claimable).to.equal(0n); // nothing harvested -> no prize
  });

  it("yield functions revert when no vault is configured (backward-compatible)", async function () {
    const { pool } = await deployAll(false); // deployed with address(0) vault
    await expect(pool.harvestYield()).to.be.revertedWith("no vault");
  });
});
